
  import { Geist, Geist_Mono, Inter } from "next/font/google";
  import "./globals.css";
  import { Metadata } from "next";

import ThemeProvider from "./ThemeProvider";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Frenin Security",
  description: "Generated by create next app",
};



/**
 * Root layout component that wraps the entire application.
 * Provides global fonts, global styles, and the theme provider.
 */
export default function RootLayout({
  children,
}: {
  /** The child components to be rendered within the layout. */
  children: React.ReactNode;
}) {
 
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-gray-50 dark:bg-dark`}
      >
      <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}